### ISSUE TITLE
Can't add the plugin. "the plugin dll could not be loaded: 126"

### ISSUE THREAD

**Issue by Tony322** [Metick/CheatEngine-DMA#1]
I compiled the plugin and tried adding it on CE 4.6 and 4.7, both gives the error "the plugin dll could not be loaded: 126", which when googling, tells me its missing a dependency. 
I copied the plugin.dll from the "plugin\x64\Release" folder into the root of CE. CE doesn't tell me more info than that either.

**Comment by vladislavix** [comment]
you indeed missing a dependency. read this: https://github.com/Metick/DMALibrary?tab=readme-ov-file#please-read.

**Comment by Tony322** [comment]
> you indeed missing a dependency. read this: https://github.com/Metick/DMALibrary?tab=readme-ov-file#please-read.

Ahh, I see! That certainly did the trick. I thought the main readme was enough. Sorry about that.
Pretty darn cool thing you got going here. Thanks a lot for this, seems to work great.

A side note, is there any way to make the mono inspector in CE to work on mono applications? I'm attached to a .NET/mono application that normally let you use those tools built into CE. Meaning this: https://wiki.cheatengine.org/index.php?title=Mono

**Comment by Metick** [comment]
You most likely could add support for it, sadly I don't have time to look into what it requires to add support for it. but you're free to add support yourself & Look into it.

I'd assume it requires VirtualAlloc ect, cuz I think it injects a lua .dll into the process? I could be wrong on this though

**Comment by vladislavix** [comment]
> A side note, is there any way to make the mono inspector in CE to work on mono applications? I'm attached to a .NET/mono application that normally let you use those tools built into CE. Meaning this: https://wiki.cheatengine.org/index.php?title=Mono

as far as I know, the cheat engine injects a specific dll into the target process that compiles all the mono-methods, so i dont think its possible

**Comment by Metick** [comment]
> > A side note, is there any way to make the mono inspector in CE to work on mono applications? I'm attached to a .NET/mono application that normally let you use those tools built into CE. Meaning this: https://wiki.cheatengine.org/index.php?title=Mono
> 
> as far as I know, the cheat engine injects a specific dll into the target process that compiles all the mono-methods, so i dont think its possible

It should be possible if you replicate Virtual Alloc ect, but i assume it uses CreateRemoteThread to execute the memory, so you'd probably have to do something like hooking a function in the game that gets called a lot on that import, or IAT hook. it just requires some manual reversing & programming to implement that part. There just isn't a "Solution for all games" type thing here that would be UD. Not to mention allocating memory on EAC/BE is detected

**Comment by Tony322** [comment]
Ahh I see. Thanks for the replies people. I'm closing this as the original issue is solved. Have a good one!
