### ISSUE TITLE
ERROR: Could not dump memory map

### ISSUE THREAD

**Issue by yeyu12** [Metick/CheatEngine-DMA#10]
Hello, after I load the plug-in, the plug-in does not run properly. And the process list cannot read the process. Please ask, what is the problem? I am a newbie in c++。
ce version 7.5

![image](https://github.com/Metick/CheatEngine-DMA/assets/12890827/3f1dae74-3670-479c-bcb6-2a32bda41076)
![image](https://github.com/Metick/CheatEngine-DMA/assets/12890827/a6ff60f8-a927-4d34-b0b2-e4ee4513e613)

**Comment by Metick** [comment]
Because it's unable to initialize to your DMA card. if you're AMD user please manually dump your physical pages and put it in %temp%/mmap.txt 

usually the library will dump them for you but on some computers (AMD specific only) it doesn't work.

**Comment by yeyu12** [comment]
My computer's CPU is i7 and my computer system is win11. Is it related to the computer system?

**Comment by Metick** [comment]
do you have a FPGA DMA device?
