### ISSUE TITLE
Missing results when scaning using cheat engine

### ISSUE THREAD

**Issue by cheng3969** [Metick/CheatEngine-DMA#11]
Hello,
I've compiled this plugin for Cheat Engine and while it's functional, I'm encountering an issue where certain search results are missing compared to standard Cheat Engine scans without plugin.
![Screenshot 2024-04-13 102117](https://github.com/Metick/CheatEngine-DMA/assets/36038316/9ac75b23-b5f7-4e35-a542-a2f8044e6694)

With plugin:
![Screenshot 2024-04-13 100613](https://github.com/Metick/CheatEngine-DMA/assets/36038316/3a6ecf09-5470-4199-89b3-8697de8b20af)

Without plugin:
![Screenshot 2024-04-13 100620](https://github.com/Metick/CheatEngine-DMA/assets/36038316/b4f2f90b-8771-4335-be20-977007718d3a)

These 3 results not showing when using plugin:
![Screenshot 2024-04-13 101203](https://github.com/Metick/CheatEngine-DMA/assets/36038316/beb8b439-b976-4d5b-9a07-c81349a6dc9a)

But i can manually add then to cheat table:
![Screenshot 2024-04-13 104049](https://github.com/Metick/CheatEngine-DMA/assets/36038316/372b1ab7-20f1-4fc9-a6f3-8a2f0fa1e968)

![Screenshot 2024-04-13 104108](https://github.com/Metick/CheatEngine-DMA/assets/36038316/68e0c144-6d68-4f71-a958-fd06dad6b22c)

I would greatly appreciate any insights into why these discrepancies occur and potential solutions.
Thank you for your expertise!

**Comment by Metick** [comment]
Hi, thanks for the information. I was aware of it myself aswell. sadly I haven't been able to figure out why this is happening, as it is scanning the memory pages correctly. which can be seen when you debug print everything. It has to do with something else I assume, just haven't had time to figure out how to solve it.

**Comment by kamuran21** [comment]
I have investigated this as well but i couldn't find the solution. I think it refers to the local memmory instead of the DMA memory.

**Comment by Metick** [comment]
> I have investigated this as well but i couldn't find the solution. I think it refers to the local memmory instead of the DMA memory.

Why would it refer to local memory? Cuz we're reading into the memory of the target application. and VirtualQuery does return the regions for the memory that's missing, but for some reason it just never shows up?

Only thing i can think of is that It might be related due to AllocationBase  being wrong in VirtualQuery, as I have no idea how to actually get the allocation base of that address space.

**Comment by Metick** [comment]
Been looking into it now for 2 days as i've started to need it for another plugin i'm making for CheatGear, but it seems like it's related to the way i currently handle code
![image](https://github.com/Metick/CheatEngine-DMA/assets/45372336/553ef916-8bfa-48fc-860f-d3179df23523)

as you can see on the screenshot above, i've been able to find static addresses to a process (in this case destiny2.exe) that i've used as a example real quick.

but sadly the way i handle code now i can't seem to read a single non-static address, LMAO. I've been on this for well over 10 hours now If anyone knows what's happening please contact me on discord. or maybe we can talk together to get this solved.

I'll continue looking into it another day again. for anyone that wants to take a look at it with me can add me on discord: conditions

**Comment by Metick** [comment]
This has been finally solved.
