### ISSUE TITLE
Not all memory being scanned / actual process memory not being scanned

### ISSUE THREAD

**Issue by ntqueryinformation** [Metick/CheatEngine-DMA#12]
Props to creating this, definently comes in handy when you have have pre-existing offsets of stuff.

The only downside i have seen so far, is that it doesnt properly scan the memory from what it seems, i have tried on a few of my own applications and tried on some games to test on aswell. One thing i have notices when for example scanning for array of bytes, it will get about a quarter of the way through and then it will just skip to the very end. It seems when it starts to scan the physical region it will happen. Here is a quick video of me showing comparing on my dma machine and my main pc comparing the scanning on it.

Video: (If link expires, i will re-upload) https://streamable.com/uf5v8q

**Comment by Metick** [comment]
refer to #11
