### ISSUE TITLE
Build erros :/

### ISSUE THREAD

**Issue by Planqton** [Metick/CheatEngine-DMA#16]
Hello, I attempted to compile this in Visual Studio 2022 with Visual Studio 2015 (v140) installed, but unfortunately, I encountered a bunch of errors. I tried to go through them but wasn't able to fix them. Perhaps you can help, or is there something I have overlooked?

**Comment by eXskill** [comment]
Have you changed the build mode to Release?
Have you added the missing files?

.\plugin\CheatEngine\lua53-64.lib - located in the folder with Cheat Engine
.\DMALibrary\libs\leechcore.lib - located in LeechCore/Memprocfs
.\DMALibrary\libs\vmm.lib - located in LeechCore/Memprocfs

**Comment by Planqton** [comment]
Sorry im such an dumb**** i dont set it to Relase :/ Thanks after all :)

**Comment by Planqton** [comment]
Ok Copied to the Cheat Engine folder.. Now it works :D
