### ISSUE TITLE
it dont find 2 files 

### ISSUE THREAD

**Issue by Scheater** [Metick/CheatEngine-DMA#19]
it dont find this files  ![image](https://github.com/Metick/CheatEngine-DMA/assets/141315107/c41b5ad6-e09b-44dc-abd3-f6c63ee7f951)

**Comment by Planqton** [comment]
Hello,
follow this https://www.youtube.com/watch?v=0JwMng7khxU

**Comment by Scheater** [comment]
> Hello, follow this https://www.youtube.com/watch?v=0JwMng7khxU

Tank you :)
