### ISSUE TITLE
Ask function find static address

### ISSUE THREAD

**Issue by qwer2415wy** [Metick/CheatEngine-DMA#2]
Hello bro, I saw you say you will not add anymore function you don't use, I just want to ask about find static address, I saw "Pointer scan" & "Find out what access/writes" both of them didn't work, how do you find the static when you use this DMA plugin?

**Comment by Metick** [comment]
I personally don't use it to find static addresses, i've been using it to see what's happening in memory & to scan for memory which i'll later just use the memory address in reclass + DMA plugin.

If you want, you could add support for pointer scanning. as for find out what access/writes that's basicly just debugging which is quite hard to implement iirc.

**Comment by qwer2415wy** [comment]
Got it! thank you for reply!

**Comment by qwer2415wy** [comment]
```
/*init4.callbackroutine = PointersReassigned;
	PointerReassignmentPluginID = Exported.RegisterFunction(pluginid, ptFunctionPointerchange, &init4); //adds a plugin menu item to the memory view
	if (PointerReassignmentPluginID == -1)
	{
		Exported.ShowMessage("Failure to register the pointer reassignment plugin");
		return FALSE;
	}*/
```
Did this code in your main.c for pointerscan?

**Comment by Metick** [comment]
> ```
> /*init4.callbackroutine = PointersReassigned;
> 	PointerReassignmentPluginID = Exported.RegisterFunction(pluginid, ptFunctionPointerchange, &init4); //adds a plugin menu item to the memory view
> 	if (PointerReassignmentPluginID == -1)
> 	{
> 		Exported.ShowMessage("Failure to register the pointer reassignment plugin");
> 		return FALSE;
> 	}*/
> ```
> 
> Did this code in your main.c for pointerscan?

The commented out code is a CheatEngine function, When you do something (Not sure what) All the hooked pointers become the original pointers again, using that function it auto-hooks the pointers back again. but haven't figured out why it didnt work yet.

**Comment by qwer2415wy** [comment]
Did you have discord? May I send friend request to you? I hope I can learn something from you.

**Comment by qwer2415wy** [comment]
Now potinerscan didn't show any error code, but when I use scan it just show me a 0 resault, I hope I can be your friend and learn something code base knowledge thx.

**Comment by Metick** [comment]
You can add me on discord: Conditions

**Comment by qwer2415wy** [comment]
Thx
