### ISSUE TITLE
Failed to write ?

### ISSUE THREAD

**Issue by Spookyisnice** [Metick/CheatEngine-DMA#20]
Hello so i followed the tutorial on youtube about 1 month ago and tryed it out with helldivers 2 aswell but i wasnt able to write i only was able to read memory?

**Comment by Metick** [comment]
I don't know what video or tutorial you've watched. but it probably was writing memory just fine, but the game overwrote the value instantly again. Try changing the freeze time to 1 in settings

**Comment by Spookyisnice** [comment]
Oh i completly forgot about this no actually cheat engine just freezes for me when i try to write.
