### ISSUE TITLE
dont map Memory 

### ISSUE THREAD

**Issue by Scheater** [Metick/CheatEngine-DMA#21]
initializing
initializing
Initialize DMA in advance (Required for Set Thread Context)
inizializing...
[!] Failed to open a VMM Handle
dumping memory map to file...
[!] ERROR: Could not dump memory map!
Defaulting to no memory map!
[!] Initialization failed with Memory map? Try without MMap
[!] Initialization failed! Is the DMA in use or disconnected?
Hooking Open Process 0x000000000144ED20
Hooking Read 0x000000000144ECC0
Hooking Write 0x000000000144ECD0
Hooking Virtual Query 0x000000000144EE80
Hooking CreateToolhelp32Snapshot 0x000000000144ED80
Hooking Process32First 0x000000000144ED90
Hooking Process32Next 0x000000000144EDA0
Hooking Module32First 0x000000000144EDD0
Hooking Module32Next 0x000000000144EDE0
Hooking Thread32First 0x000000000144EDB0
Hooking Thread32Next 0x000000000144EDC0
Initialized Methicc's CE DMA plugin

**Comment by Metick** [comment]
Make sure you have a DMA device, and if you do have one that it's working properly with everything installed for it.

If it still doesn't work try to create your own mmap.txt and place it in  %temp%

**Comment by Scheater** [comment]
no i dont haf a dma card i was folowing this youtube video :  https://www.youtube.com/watch?v=0JwMng7khxU

**Comment by kamuran21** [comment]
You need a DMA card, on the target computer.
