### ISSUE TITLE
Support For ZDMA?

### ISSUE THREAD

**Issue by Omnisciento** [Metick/CheatEngine-DMA#22]
Hi,

I currently have a ZDMA card. It differs from other normal DMA cards since it utilises a Thunderbolt interface and 2x100T chips:
https://github.com/ufrisk/pcileech-fpga/tree/master/ZDMA

I was following the below tutorial to get things working:
https://www.youtube.com/watch?v=0JwMng7khxU

It appears that ZDMA is not support since I get DMA initialisation failed. I think the root cause is that the Windows Driver for ZDMA requires leechcore_driver.dll:

> ZDMA requires a signed Windows kernel driver. [Download it here](https://mega.nz/file/Eb5nwZ5K#4lAN0NddlSjET-5yPgtoBp4VMmatT63cjoRkMTa5Bu0). Right click on the .inf file and select "install" in the popup menu that appears to install the driver. Additionally ZDMA requires the file leechcore_driver.dll. This file should be included in the latest downloads of PCILeech and MemProcFS.

Let me know if I'm doing anything wrong or if this is due to the project not supporting ZDMA. Thanks!

**Comment by Omnisciento** [comment]
Also I have run DMA tests to confirm my ZDMA card is working correctly when I was trying to get this all working.

**Comment by kamuran21** [comment]
If your card is supported by MemProcFS& pcileech, the plugin works. Plugin just a bridge between memprocfs and cheatengine.

**Comment by Metick** [comment]
If you're using ZDMA make sure you actually have leechcore_driver.dll inside the same folder as plugin.dll aswell.
