### ISSUE TITLE
Pointer Scanning Finds Nothing

### ISSUE THREAD

**Issue by rushuam** [Metick/CheatEngine-DMA#24]
Hi, firsty thanks for the plugin, I builded it successfully. 
My issue is that, I try to find pointers by pointer scanning tool by it returns nothing. Firstly, I created a pointer map and I think it created because the map file size is about 32mb.  Then I am using that to scan pointers again but the pointer scanning tool finds nothing. 

How can I find pointers via the plugin, is there another way?

**Comment by Metick** [comment]
Pointer scanning is not supported, you can add support for it if you want it added.
