### ISSUE TITLE
Pointer scan for this address is not working

### ISSUE THREAD

**Issue by SaSukiTB** [Metick/CheatEngine-DMA#27]
I’m not sure if I’m the only one facing this bug, but the pointer scan for this address is not working.

**Comment by Metick** [comment]
It's working fine, it just might not show up on the UI. but end results work fine

**Comment by SaSukiTB** [comment]
@Metick Its not working in my cheatengine version

**Comment by Metick** [comment]
> @Metick Its not working in my cheatengine version

then please find out what the issue is and solve it, it's a open source project for a reason <3
