### ISSUE TITLE
Doesnt work with Cheat Engine 7.5

### ISSUE THREAD

**Issue by Karky-io** [Metick/CheatEngine-DMA#4]
After building release and dragging the dll into my main Cheat Engine plugin directory, I get an error "The plugin cannot be loaded: 126"

My steps were as follows:
1) Download files
2) Build Release
3) Realize I needed leechcore.lib,vmm.lib, and lua53-64.dll.  After adding those 3 files to the directory, I successfully built and constantly get this error.  Any help would be appreciated as I'm very excited to get this working.

**Comment by Metick** [comment]
Make sure you've included FTD3XX.dll, VMM.dll, Leechcore.dll ect, inside the CheatEngine folder aswell.

**Comment by chuckmorris420** [comment]
> Make sure you've included FTD3XX.dll, VMM.dll, Leechcore.dll ect, inside the CheatEngine folder aswell.

Added the 3 listed DLL's to both the root CE folder and the plugin folder, has now changed my error from 126->127. Unsure if I'm missing some as you said "etc".

**Comment by Metick** [comment]
I personally have added symsrv.dll, vcruntime140.dll, vmm.dll, FTD3xx.dll, leechcore.dll inside cheatengine.exe folder. not sure what error 127 is, but error 126 means missing dependencies

**Comment by alukaduo09** [comment]
This project doesn't compile and has a lot of errors

**Comment by Metick** [comment]
Then maybe compile using Release, and not Debug.

**Comment by chuckmorris420** [comment]
> I personally have added symsrv.dll, vcruntime140.dll, vmm.dll, FTD3xx.dll, leechcore.dll inside cheatengine.exe folder. not sure what error 127 is, but error 126 means missing dependencies

Added all the requirements you listed using old versions from my own projects so I assume that was causing error 127. Heading to ulfrisks git and grabbing the latest files fixed this issue.

**Comment by Metick** [comment]
> > I personally have added symsrv.dll, vcruntime140.dll, vmm.dll, FTD3xx.dll, leechcore.dll inside cheatengine.exe folder. not sure what error 127 is, but error 126 means missing dependencies
> 
> Added all the requirements you listed using old versions from my own projects so I assume that was causing error 127. Heading to ulfrisks git and grabbing the latest files fixed this issue.

Happy to hear you managed to figure out the issue.

**Comment by alukaduo09** [comment]
> Then maybe compile using Release, and not Debug.

You are right, I have successfully compiled and used it. However, scanning a large amount of data can cause CE to crash

**Comment by Metick** [comment]
> > Then maybe compile using Release, and not Debug.
> 
> You are right, I have successfully compiled and used it. However, scanning a large amount of data can cause CE to crash

That's because DMA is inheritely slow, you just gotto wait for it to finish scanning all data. I'll be closing this issue now as it's original issue has been solved.
