### ISSUE TITLE
FPGA://algo=1 not working

### ISSUE THREAD

**Issue by chuckmorris420** [Metick/CheatEngine-DMA#6]
I have one of the not so compatible for DMA gigabyte motherboard's that makes me use algo=1 (Tiny Algo) in my other projects for initialization so when I first got an issue I assumed it was that and changed parameters in the attach command of your plugin.
After this change I still get an error and am unable to detect any processes on my target PC only the locally ran one's.
Here is a screenshot of the console
![image](https://github.com/Metick/CheatEngine-DMA/assets/33428878/4fb8315a-f150-43ee-93c3-7d777b51fb36)

*To clarify I am able to attach to my DMA card using another software after the error is thrown so it is not in use or disconnected.*
It throws an error after the mmap is generated claiming it failed to initialize and then will say it has Initialized and not detect anything on target PC.
![image](https://github.com/Metick/CheatEngine-DMA/assets/33428878/07df4e3b-580a-429e-85b2-25b4c4f16f30)

**Comment by Metick** [comment]
https://github.com/Metick/CheatEngine-DMA/blob/Master/DMALibrary/Memory/Memory.cpp#L33
https://github.com/Metick/CheatEngine-DMA/blob/Master/DMALibrary/Memory/Memory.cpp#L132

Just to be sure, You've modified it to algo=1 on both locations?

**Comment by chuckmorris420** [comment]
> https://github.com/Metick/CheatEngine-DMA/blob/Master/DMALibrary/Memory/Memory.cpp#L33 https://github.com/Metick/CheatEngine-DMA/blob/Master/DMALibrary/Memory/Memory.cpp#L132
> 
> Just to be sure, You've modified it to algo=1 on both locations?

Thanks for the really quick reply. Yeah that fixed it! Sorry bout that lmao.
I went looking for the init params manually and should have done a CTRL+F just to make sure there was no more.

Can close this now!
