### ISSUE TITLE
Error 126 loading plugin

### ISSUE THREAD

**Issue by EVPilot** [Metick/CheatEngine-DMA#8]
I'm unable to load the plugin after building. I do have FTD3XX.dll, leechcore.dll and vmm.dll. Anything else I could be missing? Thank you.

**Comment by Metick** [comment]
Checkout #4

**Comment by EVPilot** [comment]
I’m sorry I see the past issues now. Thank youRaul HerediaOn Mar 16, 2024, at 12:42 PM, Metick ***@***.***> wrote:﻿
Checkout #4
