### ISSUE TITLE
Can't attach the debugger to the process

### ISSUE THREAD

**Issue by kamuran21** [Metick/CheatEngine-DMA#9]
Hi, firstly, thank you so much for this amazing tool.

I can scan and find the record easly. But when I want to find out what accesses to the addresses, CE returns nothing.  Also when I try to hex address of the value i find nothing.  How can I handle to find static address of the values.

**Comment by Metick** [comment]
You'll have to manually add support for debugging, as mentioned on the repo we only support
Attach to a Process
Read Memory
Write Memory
Search Memory
Browse Memory
Module Iteration
Process Iteration

If you want to support any other feature you'll have to manually add them in, or hope i will add support for it. which is very unlikely.
